/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardTasksIndexRouteImport } from './routes/_dashboard/tasks/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/_dashboard/organizations/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/_dashboard/users/$userId'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/_dashboard/tasks/$taskId'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/_dashboard/projects/$projectId'
import { Route as DashboardOrganizationsOrgIdRouteImport } from './routes/_dashboard/organizations/$orgId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationsOrgIdRoute =
  DashboardOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/organizations/': typeof DashboardOrganizationsIndexRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/tasks/': typeof DashboardTasksIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/organizations': typeof DashboardOrganizationsIndexRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/tasks': typeof DashboardTasksIndexRoute
  '/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/_dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/_dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/_dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/_dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otp'
    | '/dashboard'
    | '/organizations/$orgId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/users/$userId'
    | '/organizations/'
    | '/projects/'
    | '/tasks/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/otp'
    | '/dashboard'
    | '/organizations/$orgId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/users/$userId'
    | '/organizations'
    | '/projects'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_dashboard/dashboard'
    | '/_dashboard/organizations/$orgId'
    | '/_dashboard/projects/$projectId'
    | '/_dashboard/tasks/$taskId'
    | '/_dashboard/users/$userId'
    | '/_dashboard/organizations/'
    | '/_dashboard/projects/'
    | '/_dashboard/tasks/'
    | '/_dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tasks/': {
      id: '/_dashboard/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizations/': {
      id: '/_dashboard/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/$userId': {
      id: '/_dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tasks/$taskId': {
      id: '/_dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId': {
      id: '/_dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizations/$orgId': {
      id: '/_dashboard/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardOrganizationsOrgIdRoute: typeof DashboardOrganizationsOrgIdRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardOrganizationsOrgIdRoute: DashboardOrganizationsOrgIdRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
